<a href="https://colab.research.google.com/github/nedith/Machine-Learning/blob/main/Edith_DiabetesLogisticRegression_Group9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Group 9**

Qn 1. Logistic regression

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix



In [ ]:
df=pd.read_csv("/content/drive/MyDrive/AI ML DS/diabetes_data/diabetes.csv")

In [ ]:
df.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
# Drop rows with missing values
df.dropna(inplace=True)

In [ ]:
# Split the data into features (X) and the target variable (y)
X = df.drop(columns=['Outcome'])
y = df['Outcome']


In [ ]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=30)


In [ ]:
# Train the logistic regression model
model = LogisticRegression(random_state=30, max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=30)

In [ ]:
# Predictions
y_pred = model.predict(X_test)

In [ ]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)


In [ ]:
# Print or log the results
print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)
print(conf_matrix)

Accuracy: 0.7727272727272727
Confusion Matrix:
[[81 23]
 [12 38]]
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.88      0.85       104
           1       0.70      0.62      0.66        50

    accuracy                           0.79       154
   macro avg       0.77      0.75      0.76       154
weighted avg       0.79      0.79      0.79       154

[[81 23]
 [12 38]]


In [ ]:
from sklearn.model_selection import GridSearchCV


In [ ]:
# Define the parameter grid
param_grid = {
    'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
    'penalty': ['l1', 'l2', 'elasticnet'],
    'C': [0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000],
    'class_weight': [None, 'balanced']
}

In [ ]:
# Create a logistic regression model
model = LogisticRegression(max_iter=10000)


In [ ]:
# Instantiate GridSearchCV with recall_macro scoring
grid_search = GridSearchCV(model, param_grid, cv=3, scoring='recall_macro')


In [ ]:
# Fit GridSearchCV to the training data
grid_search.fit(X_train, y_train)


In [ ]:
# Print the best parameters found
print("Best parameters found:")
print(grid_search.best_params_)

Best parameters found:
{'C': 1, 'class_weight': 'balanced', 'penalty': 'l2', 'solver': 'liblinear'}


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Make predictions on the test set using the best model
y_pred = grid_search.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the evaluation metrics
print("Evaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")

# Print the confusion matrix
print("\nConfusion Matrix:")
print(conf_matrix)

Evaluation Metrics:
Accuracy: 0.7727
Precision: 0.6230
Recall: 0.7600
F1-score: 0.6847

Confusion Matrix:
[[81 23]
 [12 38]]


Both models performed similarly without any noticeable differences in accuracy and other parameters.